### ISSUE TITLE
WPS client for 10.6, 10.7 and ArcGIS Pro?

### ISSUE THREAD

**Issue by mhogeweg** [52North/wpsclient4arcgis#1]
hi, do you have plans (or suggestions) to make this client available for ArcGIS 10.6, 10.7 and ArcGIS Pro?

**Comment by bpross-52n** [comment]
Hi Marten, the client should work with newer versions of ArcMap. 
Regarding ArcGIS Pro: We are happy to have a student work on a WPS client for ArcGIS Pro within this years Google Summer of Code (GSoC). Keep an eye on this repository: 

https://github.com/52North/wpsclient4arcgispro

Not much in there yet, as GSoC starts just today. But we expect the ArcGIS Pro client to have similar functionality as the one for ArcMap 10.X.

**Comment by mhogeweg** [comment]
Hi Benjamin,

I tried installing the latest download to my 10.7 desktop but it did complain about versions and did not install correctly. I can try again.

For the pro version: thanks!

Marten Hogeweg
Esri

On May 27, 2019, at 8:12 AM, Benjamin Pross <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Marten, the client should work with newer versions of ArcMap.
Regarding ArcGIS Pro: We are happy to have a student work on a WPS client for ArcGIS Pro within this years Google Summer of Code (GSoC). Keep an eye on this repository:

https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_52North_wpsclient4arcgispro&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=DT5ic5lSAWPEbOlMbi0-wThdyNdZsriSBzHQr2hO4bJKuvN9NolwvV2JRMVo7byKbLqrgpH0x5T_tBOzKBma8v9Snk1EcVKZgNNAQTQ770Q&m=e7jh0AcPowpROQwTB9IpjuvJMjJkQOlKbbHBQhybx0c&s=UGyweDb-tT-FmUnfTLQu7ZZS0mdxhFuRm3aIe8tam68&e= <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_52North_wpsclient4arcgispro&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=4GM91f93U12aQCXh4E4BVG6rpQ9cERcX5kLsbSqdwJg&m=hdv8V5Kj5fWo3H4Bvha6dgt0jDqv036BEfrPEgSXbd0&s=xoqCQ1tzrtYfBBtPSjPD0n6RgBEf3MXHSH41FGQuN1Y&e=>

Not much in there yet, as GSoC starts just today. But we expect the ArcGIS Pro client to have similar functionality as the one for ArcMap 10.X.

**Comment by bpross-52n** [comment]
Hi Marten,

I will also try it again with 10.7, just to be sure.

Best,

Benjamin

**Comment by bpross-52n** [comment]
I just tested the client with ArcMap 10.7. It works for me. Let me know if you still have problems installing the client. Any further information, e.g. screenshots of errors, would be appreciated.

**Comment by mhogeweg** [comment]
did you build the code? or use the latest available install?

**Comment by mhogeweg** [comment]
I tried the 1.3.0 build, but after install and opening ArcMap, there is no sign of WPS capabilities.

**Comment by bpross-52n** [comment]
I used the latest install. One thing I can imagine is that there are some artifacts (e.g. folders) of a previous installation of ArcMap left on your system. The client installer looks for those folders and suggests the installation path. So it could have been installed into such an older ArcMap folder. I would suggest to uninstall the client and install again, checking for the right installation path.

**Comment by bpross-52n** [comment]
I've created a new release that should suggest the right installation path also for ArcMap 10.7 and above.

**Comment by mhogeweg** [comment]
confirmed that 1.4.0 works with ArcMap 10.7
